### ISSUE TITLE
Pathway database

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmics/MetaPath#2]
Is it better if we don't force user to download all databases at the beginning.
At metaPath tag, users are allowed to download what they need.
Version information is also suggested to be provided.

**Comment by XiangruiZeng** [comment]
In step three, we will need all the pathways information. Therefore, we need them to download all the database.

**Comment by schwannden** [comment]
@XiangruiZeng @xiaoguang1988  is the issue resolved? Close the issue if it's resolved

**Comment by Caleb-Huo** [comment]
Not yet.
We will inquiry with George tomorrow about this issue.

**Comment by schwannden** [comment]
@XiangruiZeng @xiaoguang1988 is the issue resolved?

**Comment by XiangruiZeng** [comment]
George‘s opinion is that since this issue is trivial. We will deal with this issue later, maybe in future edition.
