### ISSUE TITLE
Default usage of MetaPath

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmics/MetaPath#3]
If use default setting to run MetaPath.
There is an error message:
![screen shot 2016-08-31 at 2 44 49 pm](https://cloud.githubusercontent.com/assets/6474826/18141979/9ac44624-6f89-11e6-8e7c-395dd228a388.png)

**Comment by schwannden** [comment]
Hi, this is an issue related to metaOmic, not MetaPath

**Comment by Caleb-Huo** [comment]
Yes, you are right.
I will move it to metaOmics
