### ISSUE TITLE
If I clicked on plot, the following error message would pop up.

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmics/MetaPath#4]
![screen shot 2016-08-31 at 2 47 11 pm](https://cloud.githubusercontent.com/assets/6474826/18142050/d6fe4b9e-6f89-11e6-8d9f-420be6380656.png)

**Comment by schwannden** [comment]
Hi, this is an issue related to metaOmic, not MetaPath. It is because the FRD cutoff value is too stringent. We are looking for some indicator to avoid this.

**Comment by XiangruiZeng** [comment]
I think your FDR cut off is too small.
