### ISSUE TITLE
When I tried MAPE, an error message will pop up

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmics/MetaPath#5]
![screen shot 2016-08-31 at 2 49 33 pm](https://cloud.githubusercontent.com/assets/6474826/18142135/3aac8e94-6f8a-11e6-9072-f72de812765b.png)

**Comment by XiangruiZeng** [comment]
What pathway analysis method are you using? If you are using KS test, there should be no parameter as number of DE genes.

**Comment by schwannden** [comment]
@xiaoguang1988 
This is also a metaOmics bug. Sorry for the confusion. Moved to metaOmics: https://github.com/metaOmic/metaOmics/issues/30
