### ISSUE TITLE
MetaPath 

### ISSUE THREAD

**Issue by matianzhou** [metaOmics/MetaPath#6]
Cannot create folder + Cannot open graphs in step 2:

<img width="823" alt="screen shot 2016-09-08 at 9 37 49 am" src="https://cloud.githubusercontent.com/assets/15972932/18351386/fe1be23a-75a7-11e6-986f-7c1e526d035f.png">

<img width="1213" alt="screen shot 2016-09-08 at 9 26 13 am" src="https://cloud.githubusercontent.com/assets/15972932/18351355/cdaa7440-75a7-11e6-939c-ad4977cf78bd.png">

**Comment by Caleb-Huo** [comment]
I think this should be a setwd error.

**Comment by matianzhou** [comment]
I tried both initiating from R or R studio, and attempted changing working directory to a name without space, but still did not solve. Let me check on the code "dir.create(dir.path)"

**Comment by matianzhou** [comment]
Works when I manually create a folder called Meta PATH, so the folder is not automatically created?

**Comment by Caleb-Huo** [comment]
On my end, my folder is automatically created.
I think it should be a issue that:
we fail to create a folder if the path name contains a space in it.

**Comment by matianzhou** [comment]
My current folder does not contain a space:

/Users/matianzhou/Documents/MetaOmicsDemo

**Comment by matianzhou** [comment]
Resolved in the newest version 0.2.4
